version: '3'
services:
  internfinder-db:
    image: mysql/mysql-server:latest

    environment:
      - STREAM_SLEEP=20
      - JVM_OPTS=-Xmx1024m -Xms512m
      - MYSQL_ROOT_PASSWORD=@Joaninah1
      - MYSQL_DATABASE=internshipManager

    ports:
      - 3300:3306

  internfinder-backend:
    image: joaninamulwa/internshipmanager:backendv1
    depends_on:
      - internfinder-db
    environment:
      - STREAM_SLEEP=20
      - JVM_OPTS=-Xmx1024m -Xms512m
      - SPRING_DATASOURCE_URL=jdbc:mysql://internfinder-db:3306/internshipManager
      - MYSQL_DATABASE=internshipManager
      - SPRING_DATASOURCE_USERNAME=joaninah
      - SPRING_DATASOURCE_PASSWORD=@Joaninah1
    #      SPRING_APPLICATION_JSON: '{
    #                     "spring.datasource.url"  : "jdbc:mysql://localhost:3306/Library,
    #                     "spring.datasource.username" : "root",
    #                     "spring.datasource.password" : "mary@meliora",
    #                     "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #                     "spring.jpa.hibernate.ddl-auto" : "update"
    #                   }'
    ports:
      - 8081:8081
#  internfinder-frontend:
#    image: joaninamulwa/internshipmanager:frontendv1
#    depends_on:
#      - internfinder-backend
#
#    ports:
#      - 3000:4200